version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
volumes:
  jenkins_data: